// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace childTracking.Blazor.Client.Models
{
    public partial class Child
    {
        public Child()
        {
            GrowthRecords = new HashSet<GrowthRecord>();
        }

        [Key]
        public Guid ChildId { get; set; }
        public Guid? UserId { get; set; }
        public string FullName { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string BloodType { get; set; }
        public string MedicalConditions { get; set; }
        public string Allergies { get; set; }
        public string Notes { get; set; }
        public DateTime? CreatedAt { get; set; }

        public virtual ICollection<GrowthRecord> GrowthRecords { get; set; }

        
    }
    public class ChildResponse
    {
        public List<Child> all { get; set; } = new List<Child>();
    }

    public class GraphQLResponse<T>
    {
        public T Data { get; set; } = default!;
    }
}