// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace ChildTracking.Repositories.Models
{
    [DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ChildTracking.Repositories.Models")]
    public class Child
    {
        [DataMember]
        public Guid ChildId { get; set; }

        [DataMember]
        public Guid? UserId { get; set; }

        [DataMember]
        public string FullName { get; set; }

        [DataMember]
        public DateTime DateOfBirth { get; set; }

        [DataMember]
        public string Gender { get; set; }

        [DataMember]
        public string BloodType { get; set; }

        [DataMember]
        public string MedicalConditions { get; set; }

        [DataMember]
        public string Allergies { get; set; }

        [DataMember]
        public string Notes { get; set; }

        [DataMember]
        public DateTime? CreatedAt { get; set; }

        public ICollection<GrowthRecord> GrowthRecords { get; set; } = new List<GrowthRecord>();
    }
}