// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace ChildTracking.Repositories.Models
{
    public partial class GrowthRecord
    {
        [Key]
        public Guid RecordId { get; set; }

        public Guid? ChildId { get; set; }
        public DateTime MeasurementDate { get; set; }
        public decimal? Weight { get; set; }
        public decimal? Height { get; set; }
        public decimal? Bmi { get; set; }
        public decimal? HeadCircumference { get; set; }
        public string Notes { get; set; }
        public string MeasuredBy { get; set; }
        public string Status { get; set; }
        public DateTime? CreatedAt { get; set; }
        public virtual Child Child { get; set; }
    }
}