// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ChildTracking.Repositories.Models
{
    [DataContract]
    public partial class UserAccount
    {
        [DataMember]
        public int UserAccountId { get; set; }
        [DataMember]
        public string UserName { get; set; }
        [DataMember]
        public string Password { get; set; }
        [DataMember]
        public string FullName { get; set; }
        [DataMember]
        public string Email { get; set; }
        [DataMember]
        public string Phone { get; set; }
        [DataMember]
        public string EmployeeCode { get; set; }
        [DataMember]
        public int RoleId { get; set; }
        public string RequestCode { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ApplicationCode { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    }
}